### ISSUE TITLE
New Component Proposal - Button As Url

### ISSUE THREAD

**Issue by RayyanX95** [pegasystems/constellation-ui-gallery#102]
# Overview
## Description:
The Button As URL is a versatile field-level component that provides multiple display options for URLs and images. It can render content in three different modes:
1. As a primary button with a "Check" label and caret icon
2. As a clickable circular image that links to a URL
3. As a static circular image

The component is ideal for situations where you need flexible URL representation in your UI, whether it's for navigation buttons, linked profile pictures, or static image displays.

## Features:
- Multiple display modes controlled via props
- Consistent circular image styling with border
- External link handling with new tab opening
- Fallback image support
- Center-aligned content

## Dependencies:
- Material UI (@material-ui/core) for styling
- Pega Cosmos React Core (@pega/cosmos-react-core) for core components
- React for component framework

### Display Mode Selection
The component supports three display modes via the `displayURL` prop:
- `Button`: Renders a primary button with "Check" text and caret icon
- `ImageWithUrl`: Renders a clickable circular image that links to a URL
- `None`: Renders nothing
- Default/Others: Renders a static circular image

### Props:
- `value`: URL for button or image source
- `displayURL`: Display mode selection
- `link`: Optional URL for image link mode

### Styling:
- Images are rendered in a circular format (65px × 64px)
- White background with a light border
- Centered content alignment
- Consistent button styling using Cosmos design system

### Enhanced User Experience:
- Flexibility in URL representation
- Consistent styling across different display modes
- Clear visual hierarchy with centered alignment

### Design Consistency:
- Standardized image dimensions and styling
- Integration with Cosmos design system
- Uniform button and link behavior

### Code Maintainability:
- Modular component structure
- Reusable styling through Material-UI
- Clear separation of display logic
- TypeScript support for better type safety

## Usage Example:
```typescript
// Button mode
<ButtonAsUrl 
  displayURL="Button"
  value="https://example.com"
/>

// Linked image mode
<ButtonAsUrl 
  displayURL="ImageWithUrl"
  value="path/to/image.jpg"
  link="https://example.com"
/>

// Static image mode
<ButtonAsUrl 
  displayURL="Image"
  value="path/to/image.jpg"
/>
```

## Attachments:
[ButtonAsUrl.zip](https://github.com/user-attachments/files/18019408/ButtonAsUrl.zip)

**Comment by ricmars** [comment]
This is an anti-pattern - a button should not be used for a URL - Button is used to trigger action inside the application - You should be using a URL field that is rendered as image or URL.
