### ISSUE TITLE
New Component Proposal - Work Status

### ISSUE THREAD

**Issue by RayyanX95** [pegasystems/constellation-ui-gallery#104]
# WorkStatus Component

## Description
A custom field component that extends Pega's field functionality with Material-UI's TextField component. This component is designed to handle work status display and input with support for different display modes and styling options.

### Component Type
Field Component (SDK)

### Key Features
- Material-UI TextField integration
- Multiple display modes support (LABELS_LEFT, STACKED_LARGE_VAL)
- Configurable read-only states
- Error handling and validation
- Responsive design with full-width support
- Accessibility support via test IDs
- TypeScript support

### Props Interface
```typescript
interface SirarComponentLibWorkStatusProps extends PConnFieldProps {
  fieldMetadata?: any;
  label: string;
  required: boolean;
  disabled: boolean;
  value: string;
  validatemessage: string;
  status: string;
  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onBlur: (event: React.FocusEvent<HTMLInputElement>) => void;
  readOnly: boolean;
  testId: string;
  helperText: string;
  displayMode: string;
  hideLabel: boolean;
}
```

### Dependencies
- @material-ui/core
- @pega/react-sdk-components
- React

### Display Modes
1. **LABELS_LEFT**: Displays field value with label aligned to the left
2. **STACKED_LARGE_VAL**: Shows field value in a stacked layout with larger text
3. **Default**: Standard TextField display with outlined or standard variant based on readOnly state

## Implementation Details
- Uses Material-UI's TextField component for input handling
- Integrates with Pega's FieldValueList component for specific display modes
- Supports maxLength constraints through fieldMetadata
- Implements error states and helper text display
- Handles both read-only and editable states with appropriate styling

## Related Components
- FieldValueList
- StyledSirarComponentLibWorkStatusWrapper

```jsx
<SirarComponentLibWorkStatus
  label="Work Status"
  value="In Progress"
  required={true}
  displayMode="LABELS_LEFT"
  onChange={(e) => handleChange(e)}
  onBlur={(e) => handleBlur(e)}
  testId="work-status-field"
  fieldMetadata={{ maxLength: 50 }}
/>
```

## Attachments

[WorkStatus.zip](https://github.com/user-attachments/files/18021572/WorkStatus.zip)

**Comment by ricmars** [comment]
There is already a status badge component in the gallery https://github.com/pegasystems/constellation-ui-gallery/tree/master/src/components/Pega_Extensions_StatusBadge - Also this component does not follow best practice by using material UI

**Comment by MohamedBouanene** [comment]
Hello @ricmars ,
Thank you for your feedback.
The primary purpose of this component is to address the localization issue with pyStatusWork. Currently, localization does not work for the Case Status field.
To resolve this, we implemented the same code you use to format the status badge. However, we modified it to display the localized value using PCore.getLocaleUtils().getLocaleValue.
For your reference, please find the attached screenshot illustrating the implementation.

![image](https://github.com/user-attachments/assets/d93fe9be-ca70-4190-a64b-f862df883e6f)

**Comment by ricmars** [comment]
This issue is a bug and is not a component that should be in the ui gallery - You were able to workaround this issue but this is not a pattern that other customers should be using
