### ISSUE TITLE
New Proposal Component - Hidden Field Value

### ISSUE THREAD

**Issue by RayyanX95** [pegasystems/constellation-ui-gallery#105]
# Hidden Field Value Component

## Overview
A custom field component that renders a hidden value in the Pega React SDK. This component extends the base field functionality while keeping the value invisible in the UI.

## Purpose
- Allows storing and managing field values without displaying them in the user interface
- Useful for maintaining state or data that needs to be preserved but not shown to end users
- Can be used in forms where certain values need to be passed along but should remain hidden

## Technical Details
- Extends `PConnFieldProps` from the Pega React SDK
- Implements a minimal render footprint using a div element
- Supports all standard field metadata and properties

## Implementation Requirements
1. Add React import
2. Resolve type definitions for PConnFieldProps
3. Consider adding prop validation
4. Implement proper value handling
5. Add proper TypeScript types for fieldMetadata

## Dependencies
- @pega/react-sdk-components
- React

## Example Usage
```tsx
<InnovationTeam_ComponentLib_HiddenFieldValue 
  value="hidden-value"
  fieldMetadata={{
    // field configuration
  }}
/>
```
## Attachments

[HiddenFieldValue.zip](https://github.com/user-attachments/files/18021630/HiddenFieldValue.zip)

**Comment by ricmars** [comment]
We don't want to pattern of dropping hidden input into the UI - This pattern that was used in Traditional UI is not a good pattern and creates unnecessary DOM elements.
