### ISSUE TITLE
UtilityList code review

### ISSUE THREAD

**Issue by vijayjangid** [pegasystems/constellation-ui-gallery#12]
**Missing effect dependency**: `secondaryFieldTypes` should be added as dependency. The list is not updating when field types are changed alone.
https://github.com/pegasystems/constellation-ui-gallery/blob/f203893174502de6a8be6c93bb0dfdcd83d170d7/src/components/Pega_Extensions_UtilityList/index.tsx#L109

**Redundent check**: `item.pxObjClass && item.pyID ` can be removed
https://github.com/pegasystems/constellation-ui-gallery/blob/f203893174502de6a8be6c93bb0dfdcd83d170d7/src/components/Pega_Extensions_UtilityList/utils.tsx#L21

**HeadingTag should be used "h3"** for utility summary lists we are using `h3` in other places (Attachments, Stakeholders etc). Consider passing prop `headingTag='h3'`
https://github.com/pegasystems/constellation-ui-gallery/blob/f203893174502de6a8be6c93bb0dfdcd83d170d7/src/components/Pega_Extensions_UtilityList/index.tsx#L115

**Comment by ricmars** [comment]
changes approved and merged https://github.com/pegasystems/constellation-ui-gallery/commit/49c039e216c319f89a5735f3133779209723293b
