### ISSUE TITLE
Fix RTL support

### ISSUE THREAD

**Issue by ricmars** [pegasystems/constellation-ui-gallery#19]
RTL has some issues for a couple of components like the network diagram and the signature capture

**Comment by vijayjangid** [comment]
Network diagram breaks on RTL mode. React Flow doesn't seem to support RTL out of the box, a gracefull fallback could be to always enforce LTR on the ReactFlow container to avoid breaking the graph.
```jsx
 <ReactFlow dir='ltr' {...otherProps} />
```
![image](https://github.com/pegasystems/constellation-ui-gallery/assets/11829883/3c52d50d-aab3-4952-bf57-ee2bd2f60d85)

What's wrong with Signature input? Are we expecting the canvas content to flip horizontally?
![image](https://github.com/pegasystems/constellation-ui-gallery/assets/11829883/25eba329-3c82-4d8d-98d8-3b7f3e6eee82)

**Comment by ricmars** [comment]
yes the canvas should be flipped ltr too
