### ISSUE TITLE
Fix hardcoded CardDetails viewname in Kanban utils

### ISSUE THREAD

**Issue by vijayjangid** [pegasystems/constellation-ui-gallery#25]
2 places the viewname is hardcode.
https://github.com/pegasystems/constellation-ui-gallery/blob/b1a4790f3923556eb47b117c4a55120f3d1ba2fa/src/components/Pega_Extensions_KanbanBoard/utils.ts#L26
https://github.com/pegasystems/constellation-ui-gallery/blob/b1a4790f3923556eb47b117c4a55120f3d1ba2fa/src/components/Pega_Extensions_KanbanBoard/utils.ts#L34

the viewname is coming as a prop to the component: `detailsViewName` so this should be used accordingly.

PS: identified these while working on Gantt compnonent, [fixed there as part of this comment](https://github.com/pegasystems/constellation-ui-gallery/commit/a3b5b52f0a8eb856653b39867f6dd8590b9a8dbc)

**Comment by ricmars** [comment]
fixed https://github.com/pegasystems/constellation-ui-gallery/commit/abec916a9f1e4b91c59c342265a6312b43c7e363
