### ISSUE TITLE
Signature component style issue

### ISSUE THREAD

**Issue by vijayjangid** [pegasystems/constellation-ui-gallery#30]
1. Signature component buttons have customs style override, should we not just use OOTB button style and default padding within the container to avoid buttons touching the container border? (unless it's a design choice)
2. The current design have focus ring bleed issue as shown in attached screenshot below.
![Screenshot 2024-02-26 at 10 51 03 PM](https://github.com/pegasystems/constellation-ui-gallery/assets/11829883/8e73a199-2536-4f4f-a373-32ff7efde140)

**Comment by ricmars** [comment]
not really a design choice - the idea was to make the button as small as possible while using the OOB styles as much as possible - we can get them inside  the canvas by 1px to avoid the bleed
