### ISSUE TITLE
Duplicate link in Field Group As Row story

### ISSUE THREAD

**Issue by niallriddell** [pegasystems/constellation-ui-gallery#4]
https://pegasystems.github.io/constellation-ui-gallery/?path=/docs/templates-field-group-as-row--docs

Text says:  "For more details on how to use this component, see [How to implement the compare and select pattern](https://support.pega.com/discussion/how-implement-compare-and-select-pattern-constellation-ui)"

**Comment by ricmars** [comment]
this is the correct - the article covers the 2 components - the simple field group as row and the more complex table comparison
