### ISSUE TITLE
Fix components to avoid rendering issues when used within a Web Embed

### ISSUE THREAD

**Issue by vrseraphin** [pegasystems/constellation-ui-gallery#53]
Please see:  [https://docs.pega.com/bundle/platform/page/platform/user-experience/troubleshooting-web-embeds.html#ariaid-title7](url)

Noticed the following components may not properly be doing this for all markup emitted:
Calendar (?)
GanttChart (?) 
PasswordInput
Scheduler (?)
Shortcuts

(?) main return does use Configuration, but see a few other markup returns which don't

**Comment by ricmars** [comment]
fixed with https://github.com/pegasystems/constellation-ui-gallery/pull/55
