### ISSUE TITLE
Component grouping for enhanced navigation and discovery

### ISSUE THREAD

**Issue by vijayjangid** [pegasystems/constellation-ui-gallery#58]
Given the substantial number of components now present in the repository, organizing them into groups would enhance accessibility and discoverability. Given that the components are primarily categorized into three types: Field, Layout, and Widget, we propose creating these three as top-level category folders and relocating the components accordingly.

Here is the list of components for each category:
### Field
| Component Name          | Type  |
|-------------------------|-------|
| Pega_Extensions_ActionableButton | Field |
| Pega_Extensions_CaseReference | Field |
| Pega_Extensions_CheckboxTrigger | Field |
| Pega_Extensions_MaskedInput | Field |
| Pega_Extensions_PasswordInput | Field |
| Pega_Extensions_QRCode | Field |
| Pega_Extensions_Scheduler | Field |
| Pega_Extensions_SignatureCapture | Field |

### Template
| Component Name          | Type     |
|-------------------------|----------|
| Pega_Extensions_FieldGroupAsRow | Template |
| Pega_Extensions_FormFullWidth | Template |
| Pega_Extensions_RatingLayout | Template |

### Widget
| Component Name          | Type     |
|-------------------------|----------|
| Pega_Extensions_Banner | Widget |
| Pega_Extensions_Calendar | Widget |
| Pega_Extensions_CardGallery | Widget |
| Pega_Extensions_CaseLauncher | Widget |
| Pega_Extensions_ChatGenAI | Widget |
| Pega_Extensions_KanbanBoard | Widget |
| Pega_Extensions_NetworkDiagram | Widget |
| Pega_Extensions_Shortcuts | Widget |
| Pega_Extensions_UtilityList | Widget |

Does anyone anticipate encountering any difficulties with this restructuring?
NOTE: We have the similar grouping in storybook though!

cc @ricmars @niallriddell

**Comment by ricmars** [comment]
yes this would have been my preference but this is not how the DXCB works - all the components must be flat under the components directory - I just tried to create the 3 folders under src/components and publishing will no longer work - we would have to edit the publishing tool of the DXCB to get it to work and this is not worth it.
