### ISSUE TITLE
Chat GenAI component Typing indicator avatar alignment issue

### ISSUE THREAD

**Issue by vijayjangid** [pegasystems/constellation-ui-gallery#9]
<img width="957" alt="ai-robot-misaligned" src="https://github.com/pegasystems/constellation-ui-gallery/assets/11829883/438a4746-78db-4bb5-b3c5-a76814210f23">

As shown in the image, the Robot AI Typing indicator icon is misaligned.
This is potentially caused due to a style override for `svg` causing a side effect.
https://github.com/pegasystems/constellation-ui-gallery/blob/75462c7fe1d7a780c6006d22cd5db961e4887de2/src/components/Pega_Extensions_ChatGenAI/styles.ts#L13

This change seems to be done for the Icon buttons for Send & Reset. Looks like the Icon buttons are not properly used and motivating this custom style override.

**Comment by ricmars** [comment]
we should remove the display block - the icon will not show up when loaded as a Constellation DX component though because the Icon are being filtered.
