### ISSUE TITLE
Enhancement Request - Dropdown values with description - Areteans

### ISSUE THREAD

**Issue by s-thutupalli** [pegasystems/constellation-ui-gallery#91]
### Enhancement of existing dropdown component
 
**Title: Dropdown values with description.**
 
## Description
 
A search field has been introduced to facilitate easy access to the options. As users type in the search field, the options are filtered in real-time based on the entered characters. Upon selecting an option, the input field will display the chosen value.
 
## Current behaviour
 
The existing dropdown lacks descriptions for each option.
 
There is no search functionality to filter the options in the dropdown list.
 
## Expected behaviour
 
When a user selects the dropdown, they will be able to see options along with their descriptions. Additionally, users can search for options to quickly find the desired selection.
 
## Uses of this Enhancement
 
The search functionality allows users to filter values easily, eliminating the need to scroll through the entire list. Additionally, descriptions have been added for every option to enhance clarity and usability.
 
## Dependency packages
 
Material UI - @mui/material @emotion/react @emotion/styled
 
## Configurations
 
DataPage

Attached the component code and detailed description with images below.

[Dropdown_Values_With_Description_Component.docx](https://github.com/user-attachments/files/17932034/Dropdown_Values_With_Description_Component.docx)
[DropdownValueWithDescription.zip](https://github.com/user-attachments/files/17932035/DropdownValueWithDescription.zip)

**Comment by ricmars** [comment]
Such component makes sense but it should not be using material UI - I will review the code and see if this requirement can be integrated as a new component in the ui gallery using the OOB Constellation presentational component. 

Note that when more meta data is required, you can use the show details that will let you configure a read only view to show more meta about the selected object - this is the recommended pattern since it scale better and is more flexible that adding a description field.

**Comment by s-thutupalli** [comment]
Thanks Richard. We will make the corresponding code changes as per the feedback and will provide updated code in couple of days.

**Comment by ricmars** [comment]
using a decouple dp to provide a secondary piece of information is increasing the maintenance cost - also all this code is using material UI and is not ready to be merged as is into the repo - the suggested approach is to configure the single select as ;picker' and use a view to provide the additional meta data
<img width="494" alt="Screenshot 2024-12-31 at 4 37 43 PM" src="https://github.com/user-attachments/assets/5d6b9f93-d1ea-4c2a-8de0-d639704a7afd" />
<img width="714" alt="Screenshot 2024-12-31 at 4 37 15 PM" src="https://github.com/user-attachments/assets/a248a43b-3254-4c6e-b991-784ca6e8e4a8" />

**Comment by ricmars** [comment]
Rejected-  SDK only – for Constellation UI – use a single-select data reference with a picker to show additional metadata
